### ISSUE TITLE
New Github UI - Button not visible

### ISSUE THREAD

**Issue by aberus** [GarethBlain/Github-Clone-to-Sourcetree-Button#1]
GitHub updated UI and button does not shows up.

![image](https://user-images.githubusercontent.com/2404410/87251276-aca08580-c46a-11ea-9ec9-1f61916802b5.png)

**Comment by GarethBlain** [comment]
Fixed this now.
Once Google's reviewed it the new version (1.0.0) will appear on the Chrome Store. 😁

**Comment by aberus** [comment]
As it turns out, GitHub updated UI again and button doesn't shows up 😞.

Maybe one suggestion for icon. Design more align with other icons.

![image](https://user-images.githubusercontent.com/2404410/94349117-d9177700-0041-11eb-8a05-d5f6eea1794d.png)


```xml
<svg class="octicon octicon-sourcetree mr-3" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M5.5 14.4v-1.5c-2.6-1.2-4.2-3.9-4-6.7c0.3-3.5 3.4-6.3 6.9-6.2C12.1 0 15.1 3 15.1 6.7c0 2.7-1.6 5.1-4 6.2v1.5 c0 1-0.8 1.7-1.7 1.7H7.3C6.3 16.1 5.5 15.3 5.5 14.4z M9.6 14.6v-2.8l0.3-0.1c1.7-0.6 3.1-2 3.5-3.8c0.8-3.9-2.6-7.2-6.5-6.2 C5.4 2 4 3.2 3.5 4.7c-1.1 2.9 0.4 5.9 3.1 6.9l0.5 0.2v2.8H9.6z M8.9 9.4C6.9 9.8 5.2 8.1 5.6 6.1C5.8 5 6.7 4.2 7.8 4 c1.9-0.4 3.6 1.3 3.3 3.3C10.8 8.3 9.9 9.2 8.9 9.4z M8.3 5.4C7.6 5.4 7.1 6 7.1 6.7c0 0.7 0.6 1.2 1.2 1.2s1.2-0.6 1.2-1.2 C9.6 6 9 5.4 8.3 5.4z"></path></svg>
```

**Comment by GarethBlain** [comment]
> As it turns out, GitHub updated UI again and button doesn't shows up 😞.
> 
> Maybe one suggestion for icon. Design more align with other icons.
> 
> ![image](https://user-images.githubusercontent.com/2404410/94349117-d9177700-0041-11eb-8a05-d5f6eea1794d.png)
> 
> ```
> <svg class="octicon octicon-sourcetree mr-3" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M5.5 14.4v-1.5c-2.6-1.2-4.2-3.9-4-6.7c0.3-3.5 3.4-6.3 6.9-6.2C12.1 0 15.1 3 15.1 6.7c0 2.7-1.6 5.1-4 6.2v1.5 c0 1-0.8 1.7-1.7 1.7H7.3C6.3 16.1 5.5 15.3 5.5 14.4z M9.6 14.6v-2.8l0.3-0.1c1.7-0.6 3.1-2 3.5-3.8c0.8-3.9-2.6-7.2-6.5-6.2 C5.4 2 4 3.2 3.5 4.7c-1.1 2.9 0.4 5.9 3.1 6.9l0.5 0.2v2.8H9.6z M8.9 9.4C6.9 9.8 5.2 8.1 5.6 6.1C5.8 5 6.7 4.2 7.8 4 c1.9-0.4 3.6 1.3 3.3 3.3C10.8 8.3 9.9 9.2 8.9 9.4z M8.3 5.4C7.6 5.4 7.1 6 7.1 6.7c0 0.7 0.6 1.2 1.2 1.2s1.2-0.6 1.2-1.2 C9.6 6 9 5.4 8.3 5.4z"></path></svg>
> ```

Thanks @aberus. Fixed again. Not sure why github seem determed to mess with the HTML so much it's almost imposible to identify the url...

Also I kinda liked the blue icon but I can see how some might want it to match so changed it. Might make it an option... Maybe...

Will go live when Google bother...

**Comment by aberus** [comment]
It's live, thank you for fixing it.
